AllCops:
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 3.4.1
  Exclude:
    - 'vendor/**/*.rb'
    - 'db/**/*.rb'
    - 'bin/**/*'

Layout/LineLength:
  Max: 120

Style/Documentation:
  Enabled: false